language: ruby
before_install:
  - sudo apt-get install libhunspell-dev hunspell-en-us
  - gem install ffi rubygems-tasks rspec yard
rvm:
  - 1.9.3
  - 2.3.0
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
script: rake spec
